### ISSUE TITLE
Missing bones?

### ISSUE THREAD

**Issue by gvissers** [raduprv/Eternal-Lands#129]
While testing some changes[*], I noticed that a few 2d0 files refer to empty areas in bones.dds. The files in question are:
* b_bone1.2d0
* b_bone2.2d0
* b_horseskull.2d0
* b_ribs.2d0
* b_vertebrae.2d0

What happened? Did these parts never get drawn, are the texture coordinates simply wrong, or did they get lost in the gray mists of time? These objects seem to be used, e.g.
```
~> zgrep -li b_vertebrae /usr/share/eternallands/maps/*.elm.gz
/usr/share/eternallands/maps/cont2map1.elm.gz
/usr/share/eternallands/maps/cont2map10_insides.elm.gz
/usr/share/eternallands/maps/cont2map12_cave3.elm.gz
/usr/share/eternallands/maps/cont2map14_insides.elm.gz
/usr/share/eternallands/maps/cont2map15_caves.elm.gz
/usr/share/eternallands/maps/cont2map17_crypt.elm.gz
/usr/share/eternallands/maps/cont2map2.elm.gz
/usr/share/eternallands/maps/cont2map21.elm.gz
/usr/share/eternallands/maps/cont2map22.elm.gz
/usr/share/eternallands/maps/cont2map23.elm.gz
/usr/share/eternallands/maps/cont2map4.elm.gz
/usr/share/eternallands/maps/cont2map5.elm.gz
/usr/share/eternallands/maps/cont2map5_caves.elm.gz
/usr/share/eternallands/maps/cont2map8.elm.gz
/usr/share/eternallands/maps/guildmap_boc.elm.gz
/usr/share/eternallands/maps/guildmap_circle.elm.gz
/usr/share/eternallands/maps/guildmap_co.elm.gz
/usr/share/eternallands/maps/guildmap_dd.elm.gz
/usr/share/eternallands/maps/guildmap_doa.elm.gz
/usr/share/eternallands/maps/guildmap_ka.elm.gz
/usr/share/eternallands/maps/guildmap_lll.elm.gz
/usr/share/eternallands/maps/guildmap_lots.elm.gz
/usr/share/eternallands/maps/guildmap_ozu.elm.gz
/usr/share/eternallands/maps/guildmap_segv.elm.gz
/usr/share/eternallands/maps/instance_mountain.elm.gz
/usr/share/eternallands/maps/map11.elm.gz
/usr/share/eternallands/maps/map11_insides.elm.gz
/usr/share/eternallands/maps/map11_insmsch.elm.gz
/usr/share/eternallands/maps/map15f.elm.gz
/usr/share/eternallands/maps/map2_insides.elm.gz
/usr/share/eternallands/maps/map2_insidescastle.elm.gz
/usr/share/eternallands/maps/map5nf.elm.gz
/usr/share/eternallands/maps/map7_insides.elm.gz
/usr/share/eternallands/maps/maparena1.elm.gz
/usr/share/eternallands/maps/mapunderworld1.elm.gz
```

[*] After I finally convinced myself that this time, it wasn't my fault

**Comment by feeltheburn** [comment]
I'd noticed that a long time ago, but never bothered following up on it.

They DID exist, at least back in 1.7.0. At some point I found the source code for that release somewhere, and just looked in it.

It had those 4 bones drawn, but it was in a bmp file, not alpha channel like the current dds. And as well, the bones were made "brighter" in the current version. 

I've done some work and got the missing ones to be similar the existing ones. This image shows the 5 bones you listed as seen in the map editor. 

![missing-2d-bones](https://user-images.githubusercontent.com/2794779/123799977-0f439900-d8e9-11eb-9649-99fcb210ef95.jpg)

I'll grab some coordinates on maps and see how they look in the current maps, but I'll update the bones.dds file to include them.

https://el-db.com/tempstuff/bones.dds

You can download the dds file at that link and put it in your client to check them yourself.

This issue can be closed, it'll be fixed in the next official release.

**Comment by gvissers** [comment]
Great detective work, thanks Burn.
