### ISSUE TITLE
Should we remove Makefile.linux and Makefile.win as we have CMakeList.txt now?

### ISSUE THREAD

**Issue by pjbroad** [raduprv/Eternal-Lands#135]
We have two ways to build the Linux client, standard make and cmake.  I now only use cmake and have changed all the packaging builds I do to use it too.  But Makefile.linux is still available and people use it.  This means we have two places to maintain for Linux builds. I forgot to update the Makefile.linux when I removed the "x86" tag from various scripts a files elsewhere.

So, should we remove Makefile.linux?

I also use the CMakeList.txt file for the windows build, Makefile.win is not maintained now and I have no way to build using it. So we should probably remove that too.  Similarly for Makefile.osx and probably Makefile.bsd.

**Comment by gvissers** [comment]
As you know I prefer the old-style Makefile. I find it far easier to modify than the entire new[*] programming language that CMake seems to be made out of. Maybe it's simply what I'm used to, maybe it's Stockholm syndrome, I don't know. I know the Makefile will never win a prize in a beauty contest, but CMakeLists.txt just hurts my eyes. It also introduces another dependency in the build process, since we still need make to build the client.

Having said that, I can work with Cmake. I like the fact that it builds in a separate build directory (though we could alter the Makefile to do the same). It probably has better cross-platform support. And it would be nice not having to update 5 different makefiles when a file is added. So I'm not totally against the idea, but I'm not really enthusiastic either.

Makefile.bsd is probably a lost cause at this point (though I would be delighted to be shown wrong on this point). Might want to check with @raduprv  if he still uses Makefile.win at all? Makefile.osx, dunno? Looks like @bendoughty uses Xcode and not the Makefile.

[*] For some definition of "new"

**Comment by raduprv** [comment]
I think they should be kept, at the very least the Windows one.

**Comment by pjbroad** [comment]
- The windows builds I've done for the last few years use cmake and the MSYS environment.  I have [documented](https://github.com/pjbroad/el-build-methods/tree/master/windows-10/msys2) the build process.  I have no way to test the Makefile.win and it is out of date.
- The mac build do indeed use Xcode, the Makefile.osx is out of date and I have no way to fix and test it. 
- I've committed a fix for the BSD build which now uses cmake too, the Makefile.bsd does not work.

We can leave the Makefile.* files but I suggest we mark them as depreciated, at least the windows, bsd and osx ones.

**Comment by pjbroad** [comment]
Closing as done what I can.
