### ISSUE TITLE
Please add an option to delete recipes including their slots.

### ISSUE THREAD

**Issue by hussamT** [raduprv/Eternal-Lands#16]
It is only possible to add a recipe or clear a recipe slot at the moment (clearing a recipe slot keeps the empty slot). Since it is possible to accidentally add the same recipe twice, it would be nice if it was possible to delete unwanted ones.
Thank you.

**Comment by pjbroad** [comment]
A little close to the release now, I'll have a loot at it after the release has gone out.

**Comment by pjbroad** [comment]
The other option is to use the sort function.  This puts empty slots at the end of the list.

**Comment by hussamT** [comment]
Or replace it with an additional formula, but it still would be nice if I could delete the empty slot.

**Comment by pjbroad** [comment]
I've added the option but on a new branch recipe_delete_option.

**Comment by hussamT** [comment]
I tried it. It doesn't delete the slot. It simply clears it and moves it to the bottom.

**Comment by pjbroad** [comment]
Thanks for trying it.  Your description is valid but I would describe it as deleting the current slot and moving all those above down to fill the gap (what the code does).  The fact that you get an additional empty slot at the end of the list is because I keep the number of available slots constant.  In my view, that would be the expected behaviour as the number of slots is set from the options window (OK, you can add a slot too from the menu). With a bit more work, it could reduce the number of slots too.

**Comment by hussamT** [comment]
Ok, I didn't know the number of slots can be set from the options window. Since I can clear the slot content, sort to move the empty slot to the end, then reduce the number of slots from the options window, there technically is no real bug here, correct?

**Comment by pjbroad** [comment]
I didn't think we were talking about a bug at all :)  I'm happy that a delete option is a useful new feature, even with the clear+sort option.  My implementation just behaved slightly different to how you imagined.  I'd be happy to make it behave as you imagined.  Unfortunately, we do know whether the number of slots was set from the options window or by adding additional slots one at a time (using the menu option) so we will have to perhaps compromise on expected behaviour.

**Comment by hussamT** [comment]
Another option would be 'remove empty slots' which would sort so blank slots are moved to the end then it reduces the amount of slots to the number of non blank ones.
Either way, I am happy there is an option from HUD preferences to reduce the number of slots. I wasn't aware of that option when I posted here. I don't mind doing it manually.

**Comment by pjbroad** [comment]
OK.  But that 's a good idea, a menu option to remove empty slots would be simple to.
