### ISSUE TITLE
compile error with gcc 7.1.1

### ISSUE THREAD

**Issue by hussamT** [raduprv/Eternal-Lands#42]
icon_window.cpp: In member function ‘virtual std::pair<float, float> IconWindow::Basic_Icon::get_uv()’:
icon_window.cpp:357:46: error: call of overloaded ‘abs(Uint32)’ is ambiguous
    if (abs(SDL_GetTicks() - last_flash_change) > 250)

Is the abs here necessary for a 32bit unsigned integer?

**Comment by gvissers** [comment]
No, and even for signed integers I fail to see how  it's useful.

**Comment by pjbroad** [comment]
Its an attempt to allow for rollover.

**Comment by gvissers** [comment]
It doesn't protect from rollover, and it's also unnecessary. Ignoring for the time being that signed overflow is in principle undefined behaviour:
```
circe:~/tmp> cat overflow.cc
#include <cstdint>
#include <iostream>

int main()
{
    std::int32_t i = 0x7fffffff, j = i+10;
    std::uint32_t u = 0xffffffff, v = u+10;
    std::cout << j << " - " << i << " = " << (j-i) << '\n';
    std::cout << v << " - " << u << " = " << (v-u) << '\n';
}
circe:~/tmp> ./overflow 
-2147483639 - 2147483647 = 10
9 - 4294967295 = 10
```
So even if the numbers were signed, rollover would be fine on all machines EL is run on without the call to abs().

**Comment by pjbroad** [comment]
Well, I've used the same pattern a few times.  I tested in the same way you show, but that was a long time ago so I can't say what went wrong.  Do you have and reference that says role-over is undefined behaviour, that seems unlikely.  Even if so, it would only kick in after running the client for many days.  Which compiler/version are you using?  This passes silently on gcc 6.3.0.  In any case, I'll go though and strip out the code.

**Comment by gvissers** [comment]
> Do you have and reference that says role-over is undefined behaviour?

The C++ standard. For instance the C++14 working draft at http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2014/n4296.pdf , section 5, note 4:

> If during the evaluation of an expression, the result is not mathematically defined or not in the range 
> of representable values for its type, the behavior is undefined.

Note that this only applies to signed integers, since unsigned integers are defined modulo 2^32 (or whatever bitsize they have). The note also recognizes that most implementations ignore signed integer overflow.

Anyway, since we're dealing with unsigned integers here, that point is rather moot. The error is meaningful, though: abs() on unsigned integers is not defined, since they cannot be negative. Rollover is handled fine (as long as you use subtraction, a test like `SDL_GetTicks() > last_flash_change + 250` might fail), so I'd vote for just removing the abs().

**Comment by pjbroad** [comment]
Fix committed.
