### ISSUE TITLE
Sound disappears when restarting

### ISSUE THREAD

**Issue by fedeb95** [raduprv/Eternal-Lands#49]
If I leave the game with audio disabled in the menu, then restart the game and enable the audio, only the music plays, but sounds such as footsteps etc. aren't played. Enabling and restarting solves the problem, but is  bit annoying. I'm using the debian build, installed with apt-get

**Comment by ElvenLord-EL** [comment]
Hello, 
This is Elven Lord (From Eternal Lands)

Yes I noticed that happens a lot, I would suggest to enter a mab or leave it, can work for a building also.

**Comment by pjbroad** [comment]
Looks like this is because the "enable sound effects" flag gets switched off if the client gets started with sound and music disabled.  Changing location should not fix it but toggling the option on should. There's a related bug in the same bit of code that turns "enable sound effects" on if off, if "enable music" is on.  I'll test the fixes a bit more before committing the changes.

**Comment by pjbroad** [comment]
Should be fixed with commit 17a8c789d0443d7e67269958595cbaf4242fb9e7.
