### ISSUE TITLE
Allow selection of player name and optionally password at the login screen

### ISSUE THREAD

**Issue by pjbroad** [raduprv/Eternal-Lands#59]
See http://www.eternal-lands.com/forum/index.php?/topic/61189-new-login-screen-for-multiple-characters/

**Comment by pjbroad** [comment]
Release in 1.9.5p4.

**Comment by moeb** [comment]
Hi, is it possible to backup the passwords of the manager? if so: how?
I falsely expected them to be stored in the .elc folder and made a backup of it.
Now my (young) characters are gone because i trusted the manager to work after reinstall.
Perhaps make the pwmanager work with gnupg like pass, if security is an issue.
Then backing up .gnupg together with .elc would solve this issue.
Elc versions are 1.9.5p6 on the old os and 1.9.5p7 on the new os.
Best regards

**Comment by pjbroad** [comment]
Sorry to hear you lost your files.  However, the files are in the ~/.elc directory tree.
.elc/main/passmngr_key
.elc/main/passmngr_logins

Are you using the snap package?  If so the files cannot not stored in $HOME/.elc due to snap confinement.  Instead all you files are stored in snap/eternallands/common/config/
snap/eternallands/common/config/main/passmngr_key
snap/eternallands/common/config/main/passmngr_logins

Hope that helps.

**Comment by moeb** [comment]
I made a mistake and copied the .elc directory as a hole into the snap dir.
Thank you for your reply and your great work. It works like a charm :+1:

**Comment by pjbroad** [comment]
I hope that means you got your data back.  When I first created the snap packages, there was no way to use the existing $HOME/.elc but there is a way now.  I would like to switch to using it, to avoid issue like this but there are complications.  Like migrating existing snap users and having to get packages approved.

**Comment by moeb** [comment]
generally i like the new `$HOME/.config/\<your prog here\>` structure the best because it unclutters the home dir.
Though for elc `$HOME/.elc` is probably best for historical reasons.

Perhaps lookup `$HOME/.config/elc`, `$HOME/snap/eternallands/...` and `$HOME/.elc` and if one of those directories exists take it. If not create `$HOME/.config/elc` ??
